# ltfb primary server ntp.conf
# with pps and serial 5071A
tos minsane 1 minclock 2
logconfig =syncevents +peerevents +sysevents +allclock

leapfile /etc/ntp/leap-seconds.list

server 127.127.22.0 # ATOM(PPS)
fudge 127.127.22.0 stratum 0 time1 0 flag2 0 flag3 1 refid LTFB
#fudge 127.127.22.0 stratum 0 time1 0 flag2 1 flag3 1 flag4 1 refid LTFB
#     flag2 1              # triggers on assert  (rising edge ?)
#     flag3 0              # enable PPS API
#     flag4 1              # enable clock timestamping
# logconfig [+|-|=][{sync|sys|peer|clock}{{,all}{info|statistics|events|status}}]...

server 127.127.47.0 maxpoll 17 # hp5071a
fudge 127.127.47.0 stratum 0            #
fudge 127.127.47.0 time1 0.534  # correct for the delay in receiving the answer from HP5071
                                # estimated from a set of 'assert' timestamps (see /home/fmeyer/ntp/assert_ltfb
                                # FM 20140725

# peer saturne.ltfb.lan   #autokey # strate 1
peer 10.10.1.7 prefer #autokey # strate 1
peer 10.10.1.14 #autokey # strate 1
peer ntp-p1.obspm.fr   #autokey # strate 1

driftfile /etc/ntp.drift        # remember the drift of the local clock

### Statistics section ###
statistics loopstats clockstats
statsdir /var/xntpd/
logfile /var/xntpd/logxntpd

filegen peerstats file peers type day link enable
filegen loopstats file loops type day link enable
filegen clockstats file clocks type day link enable
#authenticate no

keysdir /etc/ntp

## Access control section ###
enable monitor
restrict default limited kod nomodify notrap nopeer noquery
restrict -6 default limited kod nomodify notrap nopeer noquery
restrict 127.127.0.0 mask 255.255.0.0 noquery # allow referenc clocks
restrict 10.10.0.0 mask 255.255.0.0
restrict 127.0.0.1
restrict ::1
